# Generated by Django 6.0.5 on 2026-05-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
