# Generated by Django 6.0.5 on 2026-05-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_school_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
