# Generated by Django 6.0.5 on 2026-05-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Name',
            new_name='Course',
        ),
    ]
