# Generated by Django 6.0.5 on 2026-05-28 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_name_subject_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('year_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RubricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Faculty',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Name',
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PerformanceBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=2)),
                ('descriptor', models.TextField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.criterion')),
            ],
        ),
        migrations.AddField(
            model_name='criterion',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rubrictemplate'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='area',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
