# Generated by Django 6.0.5 on 2026-05-29 11:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_criterion_outcome_rubrictemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseNbr', models.CharField(default='C0000', max_length=10)),
                ('CourseName', models.CharField(max_length=25)),
                ('CourseDesc', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchoolNbr', models.CharField(default='S0000', max_length=10)),
                ('SchoolName', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=50, null=True)),
                ('Suburb', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=3, null=True)),
                ('Postcode', models.CharField(max_length=10, null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('Website', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentNbr', models.CharField(default='ST0000', max_length=10)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Year', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10, null=True)),
                ('Title', models.CharField(max_length=30)),
                ('DateOfBirth', models.DateField(null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectNbr', models.CharField(default='SB0000', max_length=10)),
                ('SubjectName', models.CharField(max_length=25)),
                ('Area', models.CharField(max_length=30)),
                ('Grade', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherNbr', models.CharField(default='T0000', max_length=10)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Faculty', models.CharField(max_length=30, null=True)),
                ('Title', models.CharField(max_length=30, null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblAssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssessmentItemNbr', models.CharField(default='AI0000', max_length=10)),
                ('AssessmentItemName', models.CharField(max_length=25)),
                ('Weighting', models.IntegerField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UnitCourse', to='app.tblcourse')),
            ],
        ),
        migrations.CreateModel(
            name='tblMarkbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarkbookNbr', models.CharField(default='MB0000', max_length=10)),
                ('MarkbookName', models.CharField(max_length=25)),
                ('MarkValue', models.IntegerField()),
                ('MarkDate', models.DateField(default=datetime.date.today)),
                ('VET', models.BooleanField(default=False)),
                ('AssessmentItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MarkbookAI', to='app.tblassessmentitem')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MarkbookCourse', to='app.tblcourse')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MarkbookTeacher', to='app.tblteacher')),
            ],
        ),
        migrations.AddField(
            model_name='tblcourse',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='School', to='app.tblschool'),
        ),
        migrations.AddField(
            model_name='tblcourse',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject', to='app.tblsubject'),
        ),
        migrations.AddField(
            model_name='tblcourse',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to='app.tblteacher'),
        ),
        migrations.CreateModel(
            name='tblUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitNbr', models.CharField(default='U0000', max_length=10)),
                ('UnitName', models.CharField(max_length=25)),
                ('UnitDesc', models.CharField(max_length=100, null=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='app.tblcourse')),
            ],
        ),
        migrations.CreateModel(
            name='tblSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubmissionNbr', models.CharField(default='S0000', max_length=10)),
                ('SubmissionName', models.CharField(max_length=25)),
                ('SubmissionMark', models.IntegerField()),
                ('SubmissionDate', models.DateField(default=datetime.date.today)),
                ('AssessmentItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubmissionAI', to='app.tblassessmentitem')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubmissionCourse', to='app.tblcourse')),
                ('Markbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubmissionMarkbook', to='app.tblmarkbook')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubmissionStudent', to='app.tblstudent')),
                ('Unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubmissionUnit', to='app.tblunit')),
            ],
        ),
        migrations.AddField(
            model_name='tblmarkbook',
            name='Unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MarkbookUnit', to='app.tblunit'),
        ),
        migrations.CreateModel(
            name='tblEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnrolmentNbr', models.CharField(default='E0000', max_length=10)),
                ('EnrolmentName', models.CharField(max_length=25)),
                ('EnrolmentDate', models.DateField(default=datetime.date.today)),
                ('StartDate', models.DateField(null=True)),
                ('EndDate', models.DateField(null=True)),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EnrolCourse', to='app.tblcourse')),
                ('School', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EnrolSchool', to='app.tblschool')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EnrolStudent', to='app.tblstudent')),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EnrolSubject', to='app.tblsubject')),
                ('Unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EnrolUnit', to='app.tblunit')),
            ],
        ),
        migrations.AddField(
            model_name='tblassessmentitem',
            name='Unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unit', to='app.tblunit'),
        ),
    ]
