# Generated by Django 6.0.5 on 2026-05-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tblcourse_tblschool_tblstudent_tblsubject_tblteacher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subject',
        ),
        migrations.RenameField(
            model_name='outcome',
            old_name='subject',
            new_name='tblSubject',
        ),
        migrations.RenameField(
            model_name='rubrictemplate',
            old_name='subject',
            new_name='tblSubject',
        ),
        migrations.AddField(
            model_name='tblstudent',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
